import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { DiscoveredStock, MarketContextResponse } from "../types";

const COLORS = {
  primary: "#0F172A",
  muted: "#475569",
  accent: "#2563EB",
  buy: "#059669",
  sell: "#DC2626",
  wait: "#D97706",
  hold: "#4F46E5",
  border: "#E2E8F0",
  cream: "#F8FAFC",
};

export function generateDiscoveryPdf(
  stocks: DiscoveredStock[],
  horizon: string,
  timestamp?: string,
  marketContext?: MarketContextResponse | null
) {
  // Use Landscape for wide table
  const doc = new jsPDF({
    orientation: "landscape",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;
  let cursorY = margin;

  // -- 1. HEADER --
  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.setTextColor(COLORS.primary);
  doc.text("ArthaVest", margin, cursorY + 5);
  
  doc.setFontSize(10);
  doc.setTextColor(COLORS.muted);
  doc.text("Discovery Scan Summary", margin, cursorY + 12);
  
  // Right side info
  const dateStr = timestamp || new Date().toISOString();
  const formattedDate = new Date(dateStr).toLocaleString("en-IN", {
    day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit"
  });
  
  doc.setFont("helvetica", "bold");
  doc.setTextColor(COLORS.primary);
  doc.text(`Horizon: ${horizon}`, pageWidth - margin, cursorY + 5, { align: "right" });
  
  doc.setFont("helvetica", "normal");
  doc.setTextColor(COLORS.muted);
  doc.text(`Generated: ${formattedDate}`, pageWidth - margin, cursorY + 12, { align: "right" });

  cursorY += 20;

  // -- 2. MARKET CONTEXT SUMMARY --
  if (marketContext) {
    const pulse = marketContext.market_pulse;
    const econ = marketContext.economic;
    
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(COLORS.primary);
    doc.text(
      `Macro Regime: ${pulse?.regime || "—"}  |  Pulse Score: ${pulse?.score || "—"}/100  |  Economic Regime: ${econ?.regime || "—"}`,
      margin,
      cursorY
    );
    cursorY += 8;
  }

  // -- 3. STOCKS TABLE --
  // Map stocks to table rows
  const tableData = stocks.map((s, idx) => [
    idx + 1,
    s.rank || "—",
    s.symbol,
    s.horizon || (horizon !== "ALL" ? horizon : "—"),
    s.sector || "—",
    s.close ? `₹${s.close}` : "—",
    s.change_pct ? `${s.change_pct > 0 ? "+" : ""}${s.change_pct}%` : "—",
    s.rsi ? s.rsi.toFixed(1) : "—",
    s.confidence ? `${Math.round((s.confidence > 1 ? s.confidence / 100 : s.confidence) * 100)}%` : "—",
    s.expected_return_pct ? `+${s.expected_return_pct}%` : "—",
    s.ai_reasoning || s.catalyst || "—"
  ]);

  autoTable(doc, {
    startY: cursorY,
    head: [["Sr.", "Rank", "Symbol", "Horizon", "Sector", "Price", "Change", "RSI", "Conf.", "Return", "Reasoning / Catalyst"]],
    body: tableData,
    theme: "striped",
    headStyles: { fillColor: COLORS.primary, textColor: "#FFFFFF", fontStyle: "bold" },
    bodyStyles: { textColor: COLORS.primary, fontSize: 8 },
    columnStyles: {
      0: { cellWidth: 10 },
      1: { cellWidth: 12 },
      2: { cellWidth: 20, fontStyle: "bold" },
      3: { cellWidth: 18, fontStyle: "bold" },
      4: { cellWidth: 25 }, // Sector
      5: { cellWidth: 20 }, // Price
      6: { cellWidth: 18 }, // Change
      7: { cellWidth: 12 }, // RSI
      8: { cellWidth: 14 }, // Conf.
      9: { cellWidth: 18 }, // Return
      10: { cellWidth: "auto" } // reasoning takes rest of space
    },
    margin: { left: margin, right: margin }
  });

  // -- FOOTER --
  const pageCount = (doc.internal as any).getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(COLORS.muted);
    doc.text(
      `Generated by ArthaVest AI · Not financial advice · Page ${i} of ${pageCount}`,
      doc.internal.pageSize.getWidth() / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: "center" }
    );
  }

  // File Name
  const d = new Date(dateStr);
  const months = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
  const dateFmt = `${String(d.getDate()).padStart(2, '0')}${months[d.getMonth()]}${d.getFullYear()}_${String(d.getHours()).padStart(2, '0')}${String(d.getMinutes()).padStart(2, '0')}`;
  
  const filename = `Discovery_${horizon}_${dateFmt}.pdf`;
  doc.save(filename);
}
